### ISSUE TITLE
Avoid full page reload

### ISSUE THREAD

**Issue by awerlang** [Dynalon/mdwiki#175]
I suggest to avoid full page reload when clicking in a hashbang link. It happens that the page title changes during reloading, which can be seen as an unwanted effect.

**Comment by Dynalon** [comment]
I trigger complete page reloads on purpose. The problem is that gimmicks can - by design - include external code and resources. I.e. if you use the gist gimmick, javascript code from GitHub will be loaded. More badly, if you use google maps gimmick, quite lots of code from google is injected and a global object is added to the `window` scope.

Now, if the users switches to another page and *no hard-reload* is performed, those code stays in the global scope. For larger wikis  (and future versions of MDwiki which will support more modular gimmick loading) this is terrible. After browsing deeply into the wiki, various external code sources (and possible global objects) may remain in memory for the page, and the browser will consume more and more ram.

To get around this, I purposely trigger a complete reload of mdwiki - this will flush out any unneeded external code, and reload only the code that is required to display the current page.

In a perfect world, every script provider (twitter, facebook, googlemaps, github etc.) would provide callbacks to unload/cleanly remove their code, but this is rarely the case. So for now, `flush and reload` is the only way to do it.
