### ISSUE TITLE
Can mdwiki be configured to camelcase links or [[Links]]?

### ISSUE THREAD

**Issue by holroy** [Dynalon/mdwiki#234]
I have some markdown documents using `CamelCase` links and `[[Links]]` ( or even `[[Link | Alternate text]]`). Is it possible to get mdwiki to recognise these?

**Comment by NHypothesis** [comment]
Seconded. I need to work with a ton of existing wiki docs in markdown, and I'm not about to convert every link in [[brackets]] to another style. Not gonna happen. This is the only showstopper for me using mdwiki.

Hoping this project isn't dead, because it's exactly what I've been searching for, aside from this one issue.

**Comment by xHN35RQ** [comment]
:+1: for Wiki-Style links!

**Comment by Dynalon** [comment]
Would be nice to have that but mdwiki re-uses the [marked](https://github.com/chjj/marked) markdown parser which does not support that style. Writing a markdown parser from scratch currently isn't in the development scope of mdwiki, so support of it mainy depends on whether or not marked supports it (which is IIRC not the case).
