### ISSUE TITLE
SEO 

### ISSUE THREAD

**Issue by alzhao** [Dynalon/mdwiki#255]
MD wiki looks great. I want to know if Google really can crawl these pages, as all the contents are generated by Javascript. From some reference, e.g. https://developers.google.com/webmasters/ajax-crawling/docs/getting-started?csw=1, mdwiki needs to generate some static HTML snapshot, but actually it has no server side codes.

So, does MDWiki has SEO or can be indexed by google? Is mdwiki still under development?

**Comment by Dynalon** [comment]
As you correctly inferred, since MDwiki content is solely created by Javascript it currently cannot be crawled by Google. If you rely on Google/SEO mdwiki might be a bad choice. This is also covered in the [the FAQ](http://dynalon.github.io/mdwiki/#!faq.md#Q:_Can_sites_generated_from_MDwiki_be_crawled_and_indexed_by_search_engines_like_Google?).

MDwiki is still under development. Although there were few commits in the past year due to my daytime job, I don't consider it dead.

**Comment by alzhao** [comment]
Glad to know it is still under development! Mdwiki is more used for docs, and SEO is very important! 

I recheck https://developers.google.com/webmasters/ajax-crawling/docs/getting-started?csw=1 and there is a mark: 

**This recommendation is officially deprecated as of October 2015.**

Because of this: https://googlewebmastercentral.blogspot.hk/2015/10/deprecating-our-ajax-crawling-scheme.html 

Google is able to "render and reason about JavaScript/AJAX generated content". Although not tested, but seems this solves the problem and we can use this easy and clean mdwiki.
